## numpy revision 

In [1]:
# introduction to numpy ------->
# Numpy is an open - source library of python which is used for handle scientific - calculations .

In [2]:
 # !pip install numpy 

In [3]:
import numpy as np


In [4]:
## why numpy is better than list ?
# 1) Numpy is homogenous data type and list is heterogeneous data type .
# 2) Numpy takes less memory while list take more memory .
# 3) Numpy take less execution time while list take more time then list 

In [5]:
a = [1,2,1,44]
type (a)

list

In [6]:
b = np.array(a)
b

array([ 1,  2,  1, 44])

In [7]:
type (b)

numpy.ndarray

In [8]:
a = [[1,2,3] ,[4,5,6],[7,8,9]]
b  = np.array(a)
b 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print("total row and columns " , b.shape)
print("total elements ", b.size)
print("total dimensions " , b.ndim)

total row and columns  (3, 3)
total elements  9
total dimensions  2


## user defined arrray 

In [11]:
a = []
size = int(input("enter size:"))
for i in range(size):
    val = int(input('enter item '))
    a.append(val)

# a
b = np.array(a)
b

enter size: 1
enter item  4


array([4])

## pre defined functions .

##### array creation functions 

In [12]:
# 1) np.array() – Create an array from a list or tuple.
# 2) np.zeros() – Create an array filled with zeros.
# 3) np.ones() – Create an array filled with ones.
# 4) np.arange() – Create array with regularly spaced values (like Python's range()).
# 5) np.linspace() – Create array with evenly spaced numbers over a specified range.
#6 )np.eye() – Create identity matrix (ones on the diagonal).



In [13]:
# 1) zeroes -> it will create an array in which all the values will be 0 in either one  - dimensions 
# or multi - dimensions . 

In [14]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [17]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [18]:
# 2) ones () -> it will create an array in which all the values will be 1 in either one - dimesional or multi -dimensional .

In [19]:
a = np.ones(2)
a

array([1., 1.])

In [20]:
# 3) eye() --> it will create an array in which diagonal positinaol elementswill be 1 and rest all are 0  

In [21]:
a = np.eye(3) 
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# (4). diag() ----> Using this method , we can create an array in which we can

In [23]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [24]:
b = np.diag(a)
b

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
# 5) random module -> 
# a) randint() --> it will genwrate random variable numbers in a given range .
a = np.random.randint(1,10,3)
a

array([7, 9, 1])

In [26]:
# (b). Rand() ----> It will generate random numbers in range 0-1. 

In [27]:
a = np.random.rand(4)
a

array([0.92625161, 0.72199245, 0.22522513, 0.10210313])

In [28]:
# c) seed() --> it will fix our random generated data .

In [29]:
np.random.seed(55)
a = np.random.randint(1,10,3)
a

array([8, 9, 6])


## Reshaping the Array 
n(rows)*n(columns) = n(total_elements )

In [30]:
a = np.random.randint(1,50,12)

In [31]:
a

array([38, 28, 34, 49, 36, 47, 31, 14, 31, 13, 25, 48])

In [32]:
a.size

12

In [33]:
# n(rows) * n(columns) = n(total_elements)

# TOTAL_ELEMNETS = 12
# 1*12 , 12*1
# 2*6 , 6*2
# 3*4 , 4*3

In [34]:
a 

array([38, 28, 34, 49, 36, 47, 31, 14, 31, 13, 25, 48])

In [35]:
a.reshape(2,6)

array([[38, 28, 34, 49, 36, 47],
       [31, 14, 31, 13, 25, 48]])

## Operation of an Array .

Type	Example

Arithmetic	+ - * /

Comparison	< > == !=

Aggregate	sum() mean() min() max()

Matrix	dot() transpose()

Universal (math)	sin() exp() sqrt()

In [36]:
a

array([38, 28, 34, 49, 36, 47, 31, 14, 31, 13, 25, 48])

In [37]:
a.reshape(3,4)

array([[38, 28, 34, 49],
       [36, 47, 31, 14],
       [31, 13, 25, 48]])

In [38]:
np.sum(a)

394

In [39]:
np.sum(a,axis = 0) # it returns the sum column wise 

394

In [40]:
a = np.arange(1,5).reshape(2,2)

In [41]:
a

array([[1, 2],
       [3, 4]])

In [42]:
b = np.arange (5,9) .reshape(2,2)

In [43]:
b

array([[5, 6],
       [7, 8]])

In [44]:
a+b

array([[ 6,  8],
       [10, 12]])

In [45]:
a-b

array([[-4, -4],
       [-4, -4]])

In [46]:
a**2

array([[ 1,  4],
       [ 9, 16]])

In [47]:
a

array([[1, 2],
       [3, 4]])

In [48]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [49]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [50]:
#hstack --> it will combined all the arrays in horizontally.
#vstcak --> it will combined all the arrays in vertically .

In [51]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([10,11,12,13])

In [52]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13])

In [54]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])