# NUMPY

NumPy is a super powerful Python library for numerical computing — mainly used for:

working with arrays (ndarray)

performing fast mathematical operations

handling linear algebra, Fourier transforms, and random number generation.



# installing NUMPY

In [ ]:
# numpy is an open source library that is used for scientific calculations .

## why numpy is better than list ?
# 1) list is heterogenous data typr anf numpy homogenous data type 
# 2) list take more memory as compare to numpy
# 3) list tale more time execution as compare to numpy . 

In [1]:
# !pip install numpy

In [2]:
import numpy as np

In [3]:
a = [1,45,90]
type (a)

list

In [5]:
b = np.array(a)
b

array([ 1, 45, 90])

In [6]:
type (b)

numpy.ndarray

# how can we create user  defined array ? 

In [7]:
a = []
size = int(input("enter size"))
for i in range (size):
    val = int(input("enter number:"))
    a.append(val)

#print(a)
b = np.array(a)
b

enter size 4
enter number: 12
enter number: 45
enter number: 67
enter number: 89


array([12, 45, 67, 89])

In [9]:
type (b)

numpy.ndarray

# how can we check shape , size and dimension of an array ? 

In [10]:
a = [[1,2,3,4,],[4,5,6,7],[8,9,10,11]]
b = np.array(a)
b

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
print("total shape = ", b.shape) ##shape = n(rows) , n(columns)


total shape =  (3, 4)


In [12]:
print("total elements = " , b.size) ### size = n(rows) * n(columns)

total elements =  12


In [13]:
print("total dimension = " , b.ndim) ### ndim stands for n_dimensions---> 2(x,y)

total dimension =  2


#### pre deifned functions in numpy 

In [14]:
# zeros() ----> it will return an array in which all the values all the values be 0 in .
# either one - dimensional or multi - dimensional 

In [15]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [18]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
print("total shape = ",a.shape )
print("total elements = ",a.size)

total shape =  (3,)
total elements =  3


In [21]:
print("total shape = ",b.shape )
print("total elements = ",b.size)

total shape =  (3, 3)
total elements =  9
