In [1]:
import numpy as np 

In [2]:
a = [[1,2,3] , [4,5,6] , [7,8,9]]
b = np.array(a) 
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# Functions 

In [4]:
# (1). zeros() ----> 
a = np.zeros(4) 
a

array([0., 0., 0., 0.])

In [5]:
# (2). ones() ---> It will create an array in which all the values are 1 . 
a = np.ones(4) 
a

array([1., 1., 1., 1.])

In [6]:
# (3). eye() ----> It will create an array in which digonal positional 
# elements will be 1 and rest all are 0 . 

In [10]:
a = np.eye(3) 
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# (4). diag() ----> Using this method , we can create an array in which we can
# customize our digonal positional elements . 

In [12]:
a = np.diag([1,45,67,90])
a

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 67,  0],
       [ 0,  0,  0, 90]])

In [13]:
# (5). Random Module 

In [14]:
# (a). Randint() ----> It will generate random numbers in a given range. 
# syntax: np.random.randint(min_value , max_value , total_numbers)

In [25]:
a = np.random.randint(1,10,3)
a

array([2, 5, 8])

In [26]:
# (b). Rand() ----> It will generate random numbers in range 0-1. 

In [29]:
a = np.random.rand(3,3) 
a

array([[0.43490264, 0.36993695, 0.2266812 ],
       [0.64848632, 0.39576714, 0.5125032 ],
       [0.96764647, 0.29689154, 0.39026585]])

In [30]:
# (c). seed() ----> It will fix our random generated data . 

In [47]:
np.random.seed(30) 
a = np.random.randint(1,10,3)
a

array([6, 6, 5])

In [48]:
# (6). view vs copy ------> 
# view means modification in original dataset . 
# copy means modification in duplicate data . 

In [51]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a[2:5]
b[:] = 0 
b

array([0, 0, 0])

In [52]:
a

array([1, 2, 0, 0, 0, 6, 7, 8, 9])

In [53]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a[2:5].copy() 
b[:] = 0 
b

array([0, 0, 0])

In [54]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])