In [32]:
import numpy as np

## Reshaping the Array 

In [2]:
# n(rows) * n(columns) = n(total_elements)

# TOTAL_ELEMNETS = 12
# 1*12 , 12*1
# 2*6 , 6*2
# 3*4 , 4*3

In [4]:
a = np.arange(1,13,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [6]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
 a.reshape(5,2) # it menas that the total multiply of rows and column are equal to the elements .

ValueError: cannot reshape array of size 12 into shape (5,2)

## Operation in array

In [13]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [14]:
a**2

array([ 1,  4,  9, 16])

In [15]:
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [17]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [18]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [19]:
a+b

array([[ 6,  8],
       [10, 12]])

In [20]:
a-b

array([[-4, -4],
       [-4, -4]])

In [21]:
a*b ## not performed as same add and subt

array([[ 5, 12],
       [21, 32]])

In [22]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [24]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a = a.reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.sum(a)

45

In [28]:
np.sum(a,axis = 0) # it returns the sum column wise 

array([12, 15, 18])

In [29]:
np.sum(a,axis = 1) # it returns the sum as row wise 

array([ 6, 15, 24])

#### UNIQUE()

it will return unique elements of array and its indexing and total occurence .

In [30]:
a = np.array([1,2,2,1,2,3,4,4,5])
np.unique(a,return_index = True , return_counts = True)

(array([1, 2, 3, 4, 5]),
 array([0, 1, 5, 6, 8], dtype=int64),
 array([2, 3, 1, 2, 1], dtype=int64))

In [31]:
# first return the elements 
# second return the indexing of an elements
# third return the count of a elements

#### LINSPACE()

It will create an array in which gap of values will be equal.

In [39]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

####  Hstack and Vstack

 np.hstack – Horizontal Stack

Stacks arrays horizontally (i.e., along columns).

The arrays must have the same number of rows.

In [40]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])

In [41]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [46]:


a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

result = np.hstack((a, b))

# Output:
# [[1 2 5 6]
#  [3 4 7 8]]


 np.vstack – Vertical Stack

Stacks arrays vertically (i.e., along rows).

The arrays must have the same number of columns.


In [42]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
result = np.vstack((a, b))


In [53]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

result = np.hstack((a, b))

# Output:
# [[1 2 5 6]
#  [3 4 7 8]]
